apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: transport
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
    - port: 2888
      targetPort: 2888
      protocol: TCP
      name: server
    - port: 3888
      targetPort: 3888
      protocol: TCP
      name: election
  clusterIP: None