version : '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: urbanmove-users-db
    environment:
      POSTGRES_DB: urbanmove_users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - urbanmove-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: .
    container_name: user-management-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urbanmove_users_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - urbanmove-network

networks:
  urbanmove-network:
    driver: bridge

volumes:
  postgres_data: